### ISSUE TITLE
Issue while installing it in my system

### ISSUE THREAD

**Issue by msambastha** [aniketbabariya24/tough-health-8180#53]
Error while connecting to The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.

Could you help me with this and why I am getting this error?

**Comment by msambastha** [comment]
Solved it by adding connectionstring to mongoDB to Environment variable, but what should be process.env.PORT?

I would really suggest the README file should be made more ellaborative.

**Comment by Amanmandal-M** [comment]
Is it resolved ?  @msambastha

**Comment by msambastha** [comment]
No, I face new issues. What is the admin credentials? When Book Services is clicked, there is no data displayed. appointment.html page is not working. @Amanmandal-M 

Also, can we assign doctors to services? If yes, how?

**Comment by Amanmandal-M** [comment]
Ok we will connect tomorrow.
